const ACTION_TYPES ={
    //counter
    INCREMENT:'INCREMENT',
    DECREMENT:'DECREMENT',
    SET_STEP:'SET_STEP',
    // to-do
    CREATED_TASK:"CREATED_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    DELETE_TASK:"DELETE_TASK",
}

export default ACTION_TYPES